### ISSUE TITLE
Use my own dataset

### ISSUE THREAD

**Issue by libaimi3270** [squareRoot3/FusedGW-Entity-Alignment#2]
Hello, thank you for your contribution to the entity extraction of the knowledge graph, I would like to ask if I use my own dataset to complete the knowledge graph alignment work first, what kind of pre-training of the dataset is needed?

**Comment by squareRoot3** [comment]
Hi! You can use any pre-trained language model in HuggingFace for eneity name (and attribute) embedding instead of pre-training it by yourself. In this project, I mainly use LaBSE and SimCSE in gwea_utils.py Line 162-187

**Comment by libaimi3270** [comment]
Thank you very much for your answer！！！！how did ent_emb.npy and rel_emb.npy come from in the data file?

**Comment by squareRoot3** [comment]
They are from the code I mentioned, 'cal_rel_emb' and 'cal_ent_emb'. You can also refer to these scripts. 
[FGWEA.zip](https://github.com/squareRoot3/FusedGW-Entity-Alignment/files/14573997/FGWEA.zip)
